spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/psyconnect_db
    username: postgres
    password: admin123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: kauelimasousa02@gmail.com
    password: zpzf wbgw jvhv ljes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8096
